"""
Smoke test: try to invoke LookAtEntry's CmdQuery_Click programmatically.

Strategy:
  1. copy CBDB_BJ_User.mdb to a temp location (non-destructive)
  2. open via Access COM
  3. populate ZZ_SCRATCH_ENTRY_CODE with code 36 (yin privilege: general)
  4. open LookAtEntry form
  5. set form controls
  6. invoke CmdQuery_Click via Application.Run
  7. read ZZ_SCRATCH_ENTRY row count
  8. cleanup
"""
from __future__ import annotations
import io, shutil, time, sys, traceback, subprocess
from pathlib import Path
import win32com.client
import pyodbc

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "CBDB_BJ_User.mdb"
COPY = ROOT / "analysis" / "_test_copy.mdb"


def main():
    # --- prep copy ---
    if COPY.exists():
        COPY.unlink()
    shutil.copy2(SRC, COPY)
    print(f"copied to {COPY}")

    # --- open Access ---
    app = win32com.client.Dispatch("Access.Application")
    app.Visible = False
    app.OpenCurrentDatabase(str(COPY))
    print("opened Access")

    # remove broken VBA references (DAO 3.6 etc.) and add the correct one
    proj = app.VBE.VBProjects(1)
    needs_dao = False
    for r in list(proj.References):
        if r.IsBroken:
            full = getattr(r, "FullPath", "") or ""
            print(f"  removing broken ref: {full}")
            if "dao" in full.lower():
                needs_dao = True
            proj.References.Remove(r)
    if needs_dao:
        for cand in (
            r"C:\Program Files\Microsoft Office\root\Office16\ACEDAO.DLL",
            r"C:\Program Files (x86)\Microsoft Office\root\Office16\ACEDAO.DLL",
        ):
            if Path(cand).exists():
                proj.References.AddFromFile(cand)
                print(f"  added DAO: {cand}")
                break

    # --- pyodbc for table I/O ---
    conn_str = f"DRIVER={{Microsoft Access Driver (*.mdb, *.accdb)}};DBQ={COPY};"
    conn = pyodbc.connect(conn_str, autocommit=True)

    try:
        cur = conn.cursor()
        # Wipe scratch tables
        cur.execute("DELETE FROM ZZ_SCRATCH_ENTRY_CODE")
        cur.execute("DELETE FROM ZZ_SCRATCH_ENTRY")
        cur.execute("DELETE FROM ZZ_SCRATCH_ADDR")
        cur.execute("DELETE FROM ZZ_SCRATCH_ADDR_LIST")
        # Insert one entry code: 36 = yin privilege: general (per HelpFile example)
        # We'll auto-discover the right code id from ENTRY_CODES table
        cur.execute("SELECT c_entry_code, c_entry_desc, c_entry_desc_chn FROM ENTRY_CODES WHERE c_entry_desc LIKE 'yin privilege%'")
        rows = cur.fetchall()
        print("yin-privilege codes:")
        for r in rows:
            print(f"  {r}")
        # pick "yin privilege: general"
        code_general = None
        for r in rows:
            if r.c_entry_desc and "general" in r.c_entry_desc.lower():
                code_general = int(r.c_entry_code)
                break
        if code_general is None:
            code_general = int(rows[0].c_entry_code)
        print(f"using entry code: {code_general}")
        cur.execute(f"INSERT INTO ZZ_SCRATCH_ENTRY_CODE (c_entry_code) VALUES ({code_general})")

        # --- inject a Standard Module with public wrappers ---
        # vbext_ct_StdModule = 1
        try:
            modname = "TestHelpers"
            try:
                comp = proj.VBComponents(modname)
            except Exception:
                comp = proj.VBComponents.Add(1)
                comp.Name = modname
            cm = comp.CodeModule
            # clear and add
            if cm.CountOfLines:
                cm.DeleteLines(1, cm.CountOfLines)
            wrapper = (
                "Option Compare Database\n"
                "Option Explicit\n"
                "\n"
                "' Generated by automated test harness — wrappers around private form events.\n"
                "Public Sub TestRun_LookAtEntry()\n"
                "    Forms!LookAtEntry.TestRunQuery\n"
                "End Sub\n"
                "\n"
                "Public Sub TestSetCtl(formName As String, ctlName As String, val As Variant)\n"
                "    Dim ctl As Control\n"
                "    Set ctl = Forms(formName).Controls(ctlName)\n"
                "    ctl.SetFocus\n"
                "    ctl.Value = val\n"
                "End Sub\n"
            )
            cm.AddFromString(wrapper)
            print(f"created std module {modname}")
        except Exception as e:
            print(f"  std module injection failed: {e}")

        # also add a Public wrapper inside Form_LookAtEntry that calls CmdQuery_Click
        try:
            comp = proj.VBComponents("Form_LookAtEntry")
            cm = comp.CodeModule
            # only add once
            if "TestRunQuery" not in cm.Lines(1, cm.CountOfLines):
                cm.AddFromString("\nPublic Sub TestRunQuery()\n    Call CmdQuery_Click\nEnd Sub\n")
                print("injected TestRunQuery wrapper into form module")
        except Exception as e:
            print(f"  form wrapper injection failed: {e}")

        # explicitly compile the project (acCmdCompileAllModules = 126)
        try:
            app.DoCmd.RunCommand(126)
            print("compiled project")
        except Exception as e:
            print(f"  compile failed: {e}")

        # --- open form ---
        app.DoCmd.OpenForm("LookAtEntry", 0, "", "", 0, 1)  # acFormView, hidden
        f = app.Forms("LookAtEntry")
        print("opened form LookAtEntry")

        # set controls (need SetFocus first)
        def setctl(name, val):
            c = f.Controls(name)
            try: c.SetFocus()
            except Exception: pass
            c.Value = val

        setctl("TxtFromYear", 900)
        setctl("TxtToYear", 1100)
        setctl("FrameYears", 2)             # 2 = Index Years
        setctl("TxtEntryDesc", "yin privilege: general")
        setctl("TxtTypeCode", "N/A")
        # crucial: gUseADDRID etc. are public globals; Form_Open sets them. Default = False.

        # --- try invoking CmdQuery_Click via injected wrapper ---
        candidates = [
            "TestHelpers.TestRun_LookAtEntry",
            "TestRun_LookAtEntry",
            "Form_LookAtEntry.TestRunQuery",
            "[Form_LookAtEntry].TestRunQuery",
        ]
        invoked = False
        for c in candidates:
            try:
                app.Run(c)
                print(f"invoked via Application.Run({c!r})")
                invoked = True
                break
            except Exception as e:
                print(f"  Run({c!r}) failed: {e}")
        if not invoked:
            print("falling back to manual SQL replay")
            return

        # --- read result ---
        cur.execute("SELECT COUNT(*) FROM ZZ_SCRATCH_ENTRY")
        n = cur.fetchone()[0]
        print(f"ZZ_SCRATCH_ENTRY row count after query: {n}")

        # also count distinct people
        cur.execute("SELECT COUNT(DISTINCT c_personid) FROM ZZ_SCRATCH_ENTRY")
        d = cur.fetchone()[0]
        print(f"distinct persons: {d}")

    finally:
        try:
            conn.close()
        except Exception:
            pass
        try:
            app.CloseCurrentDatabase()
        except Exception:
            pass
        try:
            app.Quit()
        except Exception:
            pass
        subprocess.run(["taskkill", "/F", "/IM", "MSACCESS.EXE"], capture_output=True)


if __name__ == "__main__":
    try:
        main()
    except Exception:
        traceback.print_exc()
